name: Exemplo Input
run-name: Exemplo workflow para inputm, executado por ${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            versao:
                type: string
                required: true
                default: "dev"
                description: "Versão da nova release"
            numero_card:
                type: number
                required: true
                description: "Numero do card da tarefa deste commit"
            fazer_deploy:
                type: boolean
                required: true
                description: "Especifica se deve ou não realizar o deploy"
            ambiente:
                type: choice
                required: true
                description: "Ambiente de Deploy"
                options:
                    - Dev
                    - HML
                    - PRD
jobs:
    valores_input:
        runs-on: ubuntu-latest
        steps:
            - name: Exibindo o contexto de  input completo
              run: echo "${{ toJson(inputs)}}"
            - name: Exibibindo os valores individualmente
              run: |
                echo: "Esses são os valores repassados nos inputs"
                echo: "A versão é ${{ inputs.versao}}"  
                echo: "O Card é ${{ inputs.numero_card}}"
                echo: "Deve fazer deploy ${{ inputs.fazer_deploy}}"
                echo: "O ambiente é ${{ inputs.ambiente}}"